# Customized Web Scraping for Car Listings

In [1]:
import requests

cookies = {
    'JSESSIONID': 'F8A03E5D02511F2A22B247D170651687.ad671',
    'ViewVersion': '%7B%22en%22%3A%7B%22exclude%22%3A%7B%227bf01801-3707-433d-b5c9-35e3ac9fe5b7%22%3A1%7D%2C%22type%22%3A%22OUT%22%7D%7D',
    'CarGurusUserT': '0Hdb-193.186.4.89.1711240957773',
    'cg-ssid': '0cc9720265ec2b2af920a2f78273549e280cbe0d2586dd77635bb57f115246e7',
    'MultivariateTest': 'H4sIAAAAAAAAAE2QSw7CMAxE7%2BI1SP7HhTUCJMSG41S9O7WrJtlNPONnOys8vs%2FP%2B%2FeC2wrOATcgo4ALSPD%2BWLjt2jUNvFNq89JYde5aybIZMZudljK4GlpRwzLFNEiiZUihaKCcWw8pH1iRMvJxzbq01vMWcZYdK65ecdPK1GDSae2xnU0nuNJgSp5JgkuB6BxgMh8QnaN%2BMPO7jHXK4GDaqbftDxYOPgd5AQAA3%2BrEMEGRWBkygx4ZVXwWJikTu96hK3JsXUVtzZwwTvE%3D',
    'LSW': 'www-i-0a1afd3c0a96b246c',
    'usprivacy': '1YNN',
    '_gcl_au': '1.1.1734913529.1711240963',
    '_gid': 'GA1.2.110986759.1711240964',
    '_sp_ses.df9a': '*',
    'sp-nuid': 'a080d64e-752a-4814-a3c0-b715d6973942',
    '__rtbh.uid': '%7B%22eventType%22%3A%22uid%22%2C%22id%22%3A%220Hdb-193.186.4.89.1711240957773%22%7D',
    '__rtbh.lid': '%7B%22eventType%22%3A%22lid%22%2C%22id%22%3A%22iBgKZzc6DGKAVii9P4CW%22%7D',
    '_fbp': 'fb.1.1711240967733.1200365972',
    '_tt_enable_cookie': '1',
    '_ttp': 'ms83HDNyV4EPXC-J3TSlBvcv05m',
    'FPID': 'FPID2.2.gfGeKuaobfrLNYY8wd7oXUsRxy8dCF%2Bh7aCCiTFhg%2Fs%3D.1711240964',
    'FPLC': 'socy9NKH7hP9WmqOYcJdIpw3vv54pZxa%2F7bFr0mdT5xDZV6N9h7ku0KrxWR%2B6xSBrVCa9WUny2F8Qlegl1juC8I%2Bh50mpVIGdI2Bd9EwtkiIFXSM4j3uKyG7DPv2mg%3D%3D',
    '_au_1d': 'AU1D-0100-001711240970-OAVKNMU7-AXPW',
    'OTGPPConsent': 'DBABLA~BVQqAAAACgA.QA',
    'builderSessionId': 'e9926bf6337f4ec6ad5f6199e32c7f64',
    'preferredContactInfo': 'Y2l0eT1IaWNrb3J5KnBvc3RhbENvZGU9MTUzNDAqc3RhdGU9UEEqY291bnRyeT1VUypob21lUG9zdGFsQ29kZT0xNTM0MCo_',
    'mySavedListings': '%7B%22id%22%3A%222d0862ec-8d2e-49a8-8aa0-cf9c117d5353%22%7D',
    '_pubcid': '0a9674d9-b226-4994-b97c-8844ccf8af07',
    '_pubcid_cst': 'zix7LPQsHA%3D%3D',
    'pbjs-unifiedid': '%7B%22TDID%22%3A%2201190ab2-c3b0-4221-9406-c754bb8256b9%22%2C%22TDID_LOOKUP%22%3A%22TRUE%22%2C%22TDID_CREATED_AT%22%3A%222024-02-24T00%3A43%3A41%22%7D',
    'pbjs-unifiedid_cst': 'zix7LPQsHA%3D%3D',
    '_lr_sampling_rate': '0',
    '_ga_FVWZ0RM4DH': 'GS1.1.1711240997.1.1.1711241313.60.0.0',
    'baseZip_asOf': '15340_1711241347361',
    'cto_bundle': '7Xu_k191WTh5czJpak1pMkE1Z2wlMkIwMG9zQldQUHE2QXVqUCUyRmh2VCUyQlJtVFpwRENVRGNtdG1yeVdUbm1YSlRuVCUyRlJZemRUMmklMkZGR3cxNzNuJTJCbEJRZVhsc2RxRVl2cmR1SlQxNUNLY2RkM0dzYUowenNaOTRoRnVYWWZVNWd3S1R1WGdEZlJaRFclMkJySk1yUDhZMExneFpuMWdYM0RRJTJGM1VoZ3BXSG4yR0NSTWltZlBrJTNE',
    'dpt_cust_cookie': '2',
    '_ga_4WL8DDJFSY': 'GS1.1.1711240967.1.1.1711241356.17.0.0',
    '_uetsid': '6f69d600e97711ee88de71fdeed68cf8',
    '_uetvid': '6f6a4760e97711eeaedabd7da8e76f17',
    '_lr_retry_request': 'true',
    '_lr_env_src_ats': 'false',
    '_td': '2af71189-6e8c-4e17-87ac-2a0056156b8e',
    'OptanonConsent': 'isGpcEnabled=0&datestamp=Sun+Mar+24+2024+00%3A49%3A24+GMT%2B0000+(GMT)&version=202403.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=9adf9238-5953-4510-8c1c-13428ce877e2&interactionCount=1&isAnonUser=1&landingPath=NotLandingPage&GPPCookiesCount=1&groups=C0001%3A1%2CC0003%3A1%2CC0002%3A1%2CC0004%3A1&AwaitingReconsent=false',
    '_ga': 'GA1.2.2117667524.1711240964',
    '__gads': 'ID=08c2941d07df2471:T=1711240969:RT=1711241364:S=ALNI_MZmtw3ebwtM1mvrnISn2hxC01Il0g',
    '__gpi': 'UID=00000d8158d0fc29:T=1711240969:RT=1711241364:S=ALNI_MZ_gMLltMdqoSUvhagABZYsRsdlKA',
    '__eoi': 'ID=5b150c2d1f1ea133:T=1711240969:RT=1711241364:S=AA-AfjY25JQKlQg8uIC8dKBmuRSy',
    'datadome': 'PV~MExtc_tJTGf91VmSMRKnCiYbc~7P4Tf9pg~gtGdk3rZnFfqtChjTqjxP1n3nD8__cCD7SsV_UWYulSrZ2Kt5RasORMlXoyjvUg76zEP_5LSiZuQGmQAornTaDomU2',
    '_ga_0QS2LC2KDY': 'GS1.1.1711240967.1.1.1711241725.0.0.1997108646',
    'FPGSID': '1.1711240969.1711241731.G-0QS2LC2KDY.OqTfegPt6DYF1Nsnp-Wj0A',
    '_sp_id.df9a': '75a51069-f6ff-4b75-9ded-d9d4de3bcc10.1711240964.1.1711242106.1711240964.eb44a908-9599-4fed-a733-7297713d1b5b',
}

headers = {
    'authority': 'www.cargurus.com',
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7',
    # 'cookie': 'JSESSIONID=F8A03E5D02511F2A22B247D170651687.ad671; ViewVersion=%7B%22en%22%3A%7B%22exclude%22%3A%7B%227bf01801-3707-433d-b5c9-35e3ac9fe5b7%22%3A1%7D%2C%22type%22%3A%22OUT%22%7D%7D; CarGurusUserT=0Hdb-193.186.4.89.1711240957773; cg-ssid=0cc9720265ec2b2af920a2f78273549e280cbe0d2586dd77635bb57f115246e7; MultivariateTest=H4sIAAAAAAAAAE2QSw7CMAxE7%2BI1SP7HhTUCJMSG41S9O7WrJtlNPONnOys8vs%2FP%2B%2FeC2wrOATcgo4ALSPD%2BWLjt2jUNvFNq89JYde5aybIZMZudljK4GlpRwzLFNEiiZUihaKCcWw8pH1iRMvJxzbq01vMWcZYdK65ecdPK1GDSae2xnU0nuNJgSp5JgkuB6BxgMh8QnaN%2BMPO7jHXK4GDaqbftDxYOPgd5AQAA3%2BrEMEGRWBkygx4ZVXwWJikTu96hK3JsXUVtzZwwTvE%3D; LSW=www-i-0a1afd3c0a96b246c; usprivacy=1YNN; _gcl_au=1.1.1734913529.1711240963; _gid=GA1.2.110986759.1711240964; _sp_ses.df9a=*; sp-nuid=a080d64e-752a-4814-a3c0-b715d6973942; __rtbh.uid=%7B%22eventType%22%3A%22uid%22%2C%22id%22%3A%220Hdb-193.186.4.89.1711240957773%22%7D; __rtbh.lid=%7B%22eventType%22%3A%22lid%22%2C%22id%22%3A%22iBgKZzc6DGKAVii9P4CW%22%7D; _fbp=fb.1.1711240967733.1200365972; _tt_enable_cookie=1; _ttp=ms83HDNyV4EPXC-J3TSlBvcv05m; FPID=FPID2.2.gfGeKuaobfrLNYY8wd7oXUsRxy8dCF%2Bh7aCCiTFhg%2Fs%3D.1711240964; FPLC=socy9NKH7hP9WmqOYcJdIpw3vv54pZxa%2F7bFr0mdT5xDZV6N9h7ku0KrxWR%2B6xSBrVCa9WUny2F8Qlegl1juC8I%2Bh50mpVIGdI2Bd9EwtkiIFXSM4j3uKyG7DPv2mg%3D%3D; _au_1d=AU1D-0100-001711240970-OAVKNMU7-AXPW; OTGPPConsent=DBABLA~BVQqAAAACgA.QA; builderSessionId=e9926bf6337f4ec6ad5f6199e32c7f64; preferredContactInfo=Y2l0eT1IaWNrb3J5KnBvc3RhbENvZGU9MTUzNDAqc3RhdGU9UEEqY291bnRyeT1VUypob21lUG9zdGFsQ29kZT0xNTM0MCo_; mySavedListings=%7B%22id%22%3A%222d0862ec-8d2e-49a8-8aa0-cf9c117d5353%22%7D; _pubcid=0a9674d9-b226-4994-b97c-8844ccf8af07; _pubcid_cst=zix7LPQsHA%3D%3D; pbjs-unifiedid=%7B%22TDID%22%3A%2201190ab2-c3b0-4221-9406-c754bb8256b9%22%2C%22TDID_LOOKUP%22%3A%22TRUE%22%2C%22TDID_CREATED_AT%22%3A%222024-02-24T00%3A43%3A41%22%7D; pbjs-unifiedid_cst=zix7LPQsHA%3D%3D; _lr_sampling_rate=0; _ga_FVWZ0RM4DH=GS1.1.1711240997.1.1.1711241313.60.0.0; baseZip_asOf=15340_1711241347361; cto_bundle=7Xu_k191WTh5czJpak1pMkE1Z2wlMkIwMG9zQldQUHE2QXVqUCUyRmh2VCUyQlJtVFpwRENVRGNtdG1yeVdUbm1YSlRuVCUyRlJZemRUMmklMkZGR3cxNzNuJTJCbEJRZVhsc2RxRVl2cmR1SlQxNUNLY2RkM0dzYUowenNaOTRoRnVYWWZVNWd3S1R1WGdEZlJaRFclMkJySk1yUDhZMExneFpuMWdYM0RRJTJGM1VoZ3BXSG4yR0NSTWltZlBrJTNE; dpt_cust_cookie=2; _ga_4WL8DDJFSY=GS1.1.1711240967.1.1.1711241356.17.0.0; _uetsid=6f69d600e97711ee88de71fdeed68cf8; _uetvid=6f6a4760e97711eeaedabd7da8e76f17; _lr_retry_request=true; _lr_env_src_ats=false; _td=2af71189-6e8c-4e17-87ac-2a0056156b8e; OptanonConsent=isGpcEnabled=0&datestamp=Sun+Mar+24+2024+00%3A49%3A24+GMT%2B0000+(GMT)&version=202403.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=9adf9238-5953-4510-8c1c-13428ce877e2&interactionCount=1&isAnonUser=1&landingPath=NotLandingPage&GPPCookiesCount=1&groups=C0001%3A1%2CC0003%3A1%2CC0002%3A1%2CC0004%3A1&AwaitingReconsent=false; _ga=GA1.2.2117667524.1711240964; __gads=ID=08c2941d07df2471:T=1711240969:RT=1711241364:S=ALNI_MZmtw3ebwtM1mvrnISn2hxC01Il0g; __gpi=UID=00000d8158d0fc29:T=1711240969:RT=1711241364:S=ALNI_MZ_gMLltMdqoSUvhagABZYsRsdlKA; __eoi=ID=5b150c2d1f1ea133:T=1711240969:RT=1711241364:S=AA-AfjY25JQKlQg8uIC8dKBmuRSy; datadome=PV~MExtc_tJTGf91VmSMRKnCiYbc~7P4Tf9pg~gtGdk3rZnFfqtChjTqjxP1n3nD8__cCD7SsV_UWYulSrZ2Kt5RasORMlXoyjvUg76zEP_5LSiZuQGmQAornTaDomU2; _ga_0QS2LC2KDY=GS1.1.1711240967.1.1.1711241725.0.0.1997108646; FPGSID=1.1711240969.1711241731.G-0QS2LC2KDY.OqTfegPt6DYF1Nsnp-Wj0A; _sp_id.df9a=75a51069-f6ff-4b75-9ded-d9d4de3bcc10.1711240964.1.1711242106.1711240964.eb44a908-9599-4fed-a733-7297713d1b5b',
    'referer': 'https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?buyOnlineTypes=digital_deal&zip=15340&sourceContext=CG_Guarantee_Landing_Page',
    'sec-ch-device-memory': '4',
    'sec-ch-ua': '"Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"',
    'sec-ch-ua-arch': '"x86"',
    'sec-ch-ua-full-version-list': '"Chromium";v="122.0.6261.131", "Not(A:Brand";v="24.0.0.0", "Google Chrome";v="122.0.6261.131"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-model': '""',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
}

params = {
    'buyOnlineTypes': 'DIGITAL_DEAL',
    'searchId': '21108f0c-3e7d-42e8-8843-679b3a82045c',
    'zip': '15340',
    'distance': '50',
    'sourceContext': 'CG_Guarantee_Landing_Page',
    'inventorySearchWidgetType': 'AUTO',
    'sortDir': 'ASC',
    'sortType': 'BEST_MATCH',
    'srpVariation': 'DEFAULT_SEARCH',
    'nonShippableBaseline': '0',
    'pageReceipt': 'eyJwYWdlQWxpZ25tZW50IjpbMTgsMjFdLCJzZWVuU3BvbnNvcmVkTGlzdGluZ0lkcyI6WzM4MDIzNzA5OSwzODA1NDcyOTMsMzc5NzUyNzc1LDM4MTAxODg0Nl19',
    'pageNumber': '2',
    'filtersModified': 'true',
}

## Efficient Web Scraping for Car Listings Across Multiple Pages

In [2]:
all_products = []
# Loop through all pages
for page_number in range(1, 89):
    params['pageNumber'] = str(page_number)
# Assuming you want to scrape 88 pages
    response = requests.get('https://www.cargurus.com/Cars/searchPage.action', params=params, cookies=cookies, headers=headers)
    for i in range(len(response.json()['tiles'])):
        try:
            response.json()['tiles'][i]['data']['makeName']
            all_products.append(response.json()['tiles'][i]['data'])
        except:
            pass

## Converting Scraped Car Listings to Pandas DataFrame for Analysis

In [3]:
import pandas as pd
df = pd.json_normalize(all_products)

## Exploring Scraped Car Listings: DataFrame Overview

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936 entries, 0 to 1935
Data columns (total 86 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     1936 non-null   int64
 1   inclusionType                          1936 non-null   object
 2   listingTitle                           1936 non-null   object
 3   makeName                               1936 non-null   object
 4   modelName                              1936 non-null   object
 5   makeId                                 1936 non-null   object
 6   modelId                                1936 non-null   object
 7   carYear                                1936 non-null   int64
 8   trimName                               1925 non-null   object
 9   localizedTransmission                  1912 non-null   object
 10  bodyTypeGroupId                        1935 non-null   object
 11  bodyTypeName                           1935 non-null   object
 12  salesStatus                            1936 non-null   object
 13  options                                1920 non-null   object
 14  mileage                                1924 non-null   float64
 15  mileageString                          1924 non-null   object
 16  exteriorColorName                      1897 non-null   object
 17  normalizedExteriorColor                1936 non-null   object
 18  price                                  1936 non-null   float64
 19  priceString                            1936 non-null   object
 20  expectedPrice                          1881 non-null   float64
 21  msrp                                   645 non-null    float64
 22  expectedPriceString                    1881 non-null   object
 23  priceDifferential                      1881 non-null   float64
 24  priceDifferentialString                1881 non-null   object
 25  dealScore                              1874 non-null   float64
 26  daysOnMarket                           1936 non-null   int64
 27  dealRating                             1936 non-null   object
 28  isFeatured                             1107 non-null   object
 29  featuredTypes                          1107 non-null   object
 30  featuredPremiumType                    700 non-null    object
 31  pictureCount                           1936 non-null   int64
 32  sellerId                               1936 non-null   int64
 33  listingPartnerId                       1936 non-null   int64
 34  sellerType                             1936 non-null   object
 35  dealerName                             700 non-null    object
 36  sellerCity                             1936 non-null   object
 37  sellerRegion                           1936 non-null   object
 38  sellerPostalCode                       1936 non-null   object
 39  distance                               1936 non-null   float64
 40  serviceProviderId                      1936 non-null   int64
 41  isFranchiseDealer                      1574 non-null   object
 42  franchiseMake                          1574 non-null   object
 43  isOEMCPO                               275 non-null    object
 44  isCPO                                  397 non-null    object
 45  serviceProviderName                    1936 non-null   object
 46  phoneNumber                            1936 non-null   object
 47  phoneNumberString                      1936 non-null   object
 48  phoneNumberSMS                         1936 non-null   object
 49  supportsSms                            1936 non-null   bool
 50  buyingOption                           1936 non-null   object
 51  localizedDriveTrain                    1916 non-null   object
 52  localizedExteriorColor                 1897 non-null   object
 53  localizedInteriorColor                 1872 non-null   object
 54  sellerRating                           1783 non-null   float64
 55  reviewCount                            1783 non-null   float64
 56  howToShop                              1936 non-null   object
 57  dealerLogoUrl                          700 non-null    object
 58  offset                                 1936 non-null   int64
 59  localizedFuelType                      1920 non-null   object
 60  localizedCombinedFuelEconomy           1622 non-null   object
 61  localizedDoors                         1922 non-null   object
 62  driveTrain                             1916 non-null   object
 63  localizedEngineDisplayName             1918 non-null   object
 64  ncapOverallSafetyRating                1936 non-null   object
 65  vin                                    1936 non-null   object
 66  stockNumber                            1916 non-null   object
 67  interiorColor                          1872 non-null   object
 68  unitMileage.value                      1924 non-null   float64
 69  unitMileage.unit                       1924 non-null   object
 70  originalPictureData.url                1722 non-null   object
 71  originalPictureData.height             1718 non-null   float64
 72  originalPictureData.width              1718 non-null   float64
 73  financeDto.financingEligibilityLookup  1592 non-null   object
 74  cityFuelEconomy.value                  1622 non-null   float64
 75  cityFuelEconomy.unit                   1622 non-null   object
 76  highwayFuelEconomy.value               1622 non-null   float64
 77  highwayFuelEconomy.unit                1622 non-null   object
 78  combinedFuelEconomy.value              1622 non-null   float64
 79  combinedFuelEconomy.unit               1622 non-null   object
 80  isNationwideShipperDealer              291 non-null    object
 81  viewed                                 5 non-null      object
 82  evBatteryDto.capacity                  47 non-null     object
 83  evBatteryDto.chargingTime240V          25 non-null     object
 84  evBatteryDto.chargingTime120V          6 non-null      object
 85  evBatteryDto.range                     25 non-null     object
dtypes: bool(1), float64(15), int64(8), object(62)
memory usage: 1.3+ MB

In [5]:
df.describe(include = 'all')

,id,inclusionType,listingTitle,makeName,modelName,makeId,modelId,carYear,trimName,localizedTransmission,...,highwayFuelEconomy.value,highwayFuelEconomy.unit,combinedFuelEconomy.value,combinedFuelEconomy.unit,isNationwideShipperDealer,viewed,evBatteryDto.capacity,evBatteryDto.chargingTime240V,evBatteryDto.chargingTime120V,evBatteryDto.range
count,1.936000e+03,1936,1936,1936,1936,1936,1936,1936.000000,1925,1912,...,1622.000000,1622,1622.000000,1622,291,5,47,25,6,25
unique,NaN,1,1357,41,319,41,319,NaN,659,26,...,NaN,1,NaN,1,1,1,29,17,5,20
top,NaN,DEFAULT,2021 RAM 1500 Big Horn Crew Cab 4WD,Ford,1500,m2,d2110,NaN,Limited 4WD,8-Speed Automatic,...,NaN,MPG,NaN,MPG,True,True,0.2 kWh,5 hr,6 hr,18 mi
freq,NaN,1936,30,289,93,289,93,NaN,59,472,...,NaN,1622,NaN,1622,291,5,4,3,2,3
mean,3.772203e+08,NaN,NaN,NaN,NaN,NaN,NaN,2019.300620,NaN,NaN,...,27.038224,NaN,23.574106,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,6.389221e+06,NaN,NaN,NaN,NaN,NaN,NaN,3.815854,NaN,NaN,...,6.464234,NaN,6.463659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.903018e+08,NaN,NaN,NaN,NaN,NaN,NaN,1983.000000,NaN,NaN,...,14.000000,NaN,11.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,3.763318e+08,NaN,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN,NaN,...,23.000000,NaN,19.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,3.795303e+08,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,NaN,NaN,...,26.500000,NaN,22.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,3.808251e+08,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,...,30.000000,NaN,26.150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,3.818090e+08,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN,NaN,...,108.000000,NaN,108.550000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Analyzing Deal Scores and Ratings of Scraped Car Listings

In [6]:
# Displaying deal scores and ratings for each car listing in the DataFrame
# Deal score represents the value proposition of the car listing, while deal rating categorizes it as FAIR_PRICE, GOOD_PRICE, GREAT_PRICE, or OVERPRICED

df[['dealScore','dealRating']]

      dealScore   dealRating
0     -0.276131   FAIR_PRICE
1     -0.389160   FAIR_PRICE
2     -0.238404   FAIR_PRICE
3      1.333829  GREAT_PRICE
4      1.557620  GREAT_PRICE
...         ...          ...
1931  -1.888112   OVERPRICED
1932  -1.731011   OVERPRICED
1933  -2.266959   OVERPRICED
1934  -1.789869   OVERPRICED
1935  -1.791646   OVERPRICED

[1936 rows x 2 columns]

## Identifying Columns with Uniform Values Across Car Listings

In [7]:
# Identifying columns with only one unique value across all listings, which may not provide meaningful insights

all_columns = df.columns
unusefull_column_one_unique_value =[]
for column in all_columns:
    try :
        values = df[column].unique()
        num_values = len(values)
    except :
        values = df[column].explode()
        num_values = len(values.unique())
    if num_values == 1 :
        unusefull_column_one_unique_value.append(column)

## Detecting Columns with a Significant Number of Missing Values Across Car Listings

In [8]:
all_columns = df.columns
unusefull_column_many_missing_values ={}
for column in all_columns:
    try :
        values = df[column].count()
    except :
        values = df[column].explode()
        values = values.count()
    if values < 1700 :
        unusefull_column_many_missing_values[column]= values

## List of Columns with Substantial Missing Values Across Car Listings

In [9]:
unusefull_column_many_missing_values = list(unusefull_column_many_missing_values.keys())

## Removing Columns with Significant Missing Values from the DataFrame

In [10]:
df = df.drop(columns= unusefull_column_many_missing_values, axis = 1)

## Removing Columns with Uniform Values Across Car Listings from the DataFrame

In [11]:
df = df.drop(columns= unusefull_column_one_unique_value, axis = 1)

## Removing Redundant Columns from the DataFrame

In [13]:
df = df.drop(['id','unitMileage.unit','mileageString','unitMileage.value','offset','priceString','expectedPriceString','priceDifferentialString','phoneNumberString','phoneNumber','originalPictureData.url',
       'originalPictureData.height', 'originalPictureData.width','vin','sellerRegion','sellerCity','listingTitle','options','dealScore','price','expectedPrice','stockNumber','modelId'],axis =1)

## Checking and Removing Duplicate Entries in the DataFrame

In [14]:
print(df.shape)
df = df.drop_duplicates()
print(df.shape)

(1936, 32)
(1846, 32)

## Exporting Cleaned Car Listings Data to CSV

In [15]:
df.to_csv('cargurus.csv')